### ISSUE TITLE
Arreglos dentro del objeto

### ISSUE THREAD

**Issue by PESPESPES** [mgalante/jquery.redirect#32] opened 2017-05-30 20:56 UTC
{agencies:[{a:0},{a:1}] a:3004640,b:70115913,c:75157407 }

ChangeTermModel[a]:3004640
ChangeTermModel[b]:70115913
ChangeTermModel[c]:75157407

ChangeTermModel[EndorsementTo]:01/01/2020
ChangeTermModel[PolicyType]:2
ChangeTermModel[ag][][a]:0
ChangeTermModel[ag][][b]:0
ChangeTermModel[ag][][c]:44 -
ChangeTermModel[ag][][d]:30
ChangeTermModel[ag][][IsPrincipal]:false

no esta asignando la posicion del arreglo

ChangeTermModel[a]:3004640
ChangeTermModel[b]:70115913
ChangeTermModel[c]:75157407

deberia quedar

ChangeTermModel[EndorsementTo]:01/01/2020
ChangeTermModel[PolicyType]:2
ChangeTermModel[ag][0][a]:0
ChangeTermModel[ag][0][b]:0

ChangeTermModel[ag][0][d]:30
ChangeTermModel[ag][0][IsPrincipal]:false

queda sin la posicion cuando arma el objeto
  iterateParent.push('');
 iterateParent.push(i);

**Comment by mgalante** [comment] 2017-05-31 14:05
Duplicate of issue #12

**Closed by mgalante** 2017-05-31 14:05 UTC
